/*
 * Generated by erpcgen 1.9.0 on Tue May 17 21:35:50 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_bbcar_control_h_)
#define _bbcar_control_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief BBCarService identifiers */
enum _BBCarService_ids
{
    kBBCarService_service_id = 1,
    kBBCarService_stop_id = 1,
    kBBCarService_goStraight_id = 2,
    kBBCarService_turn_id = 3,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name BBCarService
//@{
void stop(uint8_t car);

void goStraight(uint8_t car, int32_t speed);

void turn(uint8_t car, int32_t speed, double factor);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _bbcar_control_h_
