#
# Generated by erpcgen 1.9.0 on Tue May 17 21:36:12 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for BBCarService
class IBBCarService(object):
    SERVICE_ID = 1
    STOP_ID = 1
    GOSTRAIGHT_ID = 2
    TURN_ID = 3

    def stop(self, car):
        raise NotImplementedError()

    def goStraight(self, car, speed):
        raise NotImplementedError()

    def turn(self, car, speed, factor):
        raise NotImplementedError()


