# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.9.0 on Sun Apr 17 23:11:30 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for LEDBlinkService
class LEDBlinkServiceClient(interface.ILEDBlinkService):
    def __init__(self, manager):
        super(LEDBlinkServiceClient, self).__init__()
        self._clientManager = manager

    def led3_change(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.LED3_CHANGE_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)



