# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.9.0 on Sun Apr 17 23:11:30 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for LEDBlinkService
class ILEDBlinkService(object):
    SERVICE_ID = 1
    LED3_CHANGE_ID = 1

    def led3_change(self):
        raise NotImplementedError()


