/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.9.0 on Sun Apr 17 23:11:45 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_blink_led_h_)
#define _blink_led_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief LEDBlinkService identifiers */
enum _LEDBlinkService_ids
{
    kLEDBlinkService_service_id = 1,
    kLEDBlinkService_led3_change_id = 1,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name LEDBlinkService
//@{
void led3_change(void);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _blink_led_h_
