# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.9.0 on Sun Apr 17 22:46:11 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for LEDBlinkService
class ILEDBlinkService(object):
    SERVICE_ID = 1
    LED_ON_ID = 1
    LED_OFF_ID = 2

    def led_on(self, led):
        raise NotImplementedError()

    def led_off(self, led):
        raise NotImplementedError()


